api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from . import views

urlpatterns = [
    path('latest/', views.PostView.as_view()),
    path('user-verify/', views.UserVerify.as_view()),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),
    path('api-token-verify/', views.TokenVerify.as_view(), name="api_token_verify")
]

coresight/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap

from users import views as user_views
from posts.views import IndexPostView

from coresight.sitemaps import coresight_sitemap


urlpatterns = [
    path('', IndexPostView.as_view(), name="index"),
    path('core/', admin.site.urls),
    path('users/', include('users.urls'), name='users'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    path('research/', include('posts.urls'), name="posts"),
    path('api/', include('api.urls'), name="api"),
    path('cookies/', include('cookie_consent.urls')),
    path('events/', include('events.urls')),
    path('databanks/', include('databanks.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': coresight_sitemap}, name='django.contrib.sitemaps.views.sitemap'),
]
# authentication urls
urlpatterns += [
    path(
        'login/',
        user_views.LoginView.as_view(),
        name='auth-login'
    ),
    path('signup/', user_views.RegistrationView.as_view(), name='signup'),
    path('auth/password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('auth/password_reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name='password_reset'),
    path('auth/password_reset/done/', auth_views.PasswordResetDoneView .as_view(template_name='password_reset_done.html'), name='password_reset_done'),
    re_path(r'auth/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name='password_reset_confirm'),
    path('auth/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),
    path(
        'auth/logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'premium-request',
        user_views.PremiumRequestView.as_view(),
        name='premium_request'
    )
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

users/urls.py
from django.contrib import admin
from django.urls import path, re_path

from users import views


app_name = 'users'

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view(), name='logout'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('account', views.AccountView.as_view(), name='account'),
    path(
        'plan-activate',
        views.PlanActivateView.as_view(),
        name='plan_activate'
    ),
]

coresight/templates/_category.html
<div class="cat-news">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h5>Sports</h5>
                <div class="row">
                    <div class="col-md-4">
                        <div class="cn-img">
                            <img src="{% static 'images/news-350x223-1.jpg' %}" />
                            <div class="cn-title">
                                <a href="">Lorem ipsum dolor sit</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="cn-img">
                            <img src="{% static 'images/news-350x223-2.jpg' %}" />
                            <div class="cn-title">
                                <a href="">Lorem ipsum dolor sit</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="cn-img">
                            <img src="{% static 'images/news-350x223-3.jpg' %}" />
                            <div class="cn-title">
                                <a href="">Lorem ipsum dolor sit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

coresight/templates/_headers.html
{% load static %}
    <meta charset="utf-8">
    <title>Coresight Research Labs</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Coresight Research Labs - Data and Research" name="keywords">
    <meta content="Coresight Research Labs - Data and Research" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet" /> 

    <!-- CSS Libraries -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>    
<link href="{% static 'js/lib/slick/slick.css' %}" rel="stylesheet" />
    <link href="{% static 'js/lib/slick/slick-theme.css' %}" rel="stylesheet" />
    <link href="https://vjs.zencdn.net/7.18.1/video-js.css" rel="stylesheet" />

    <!-- Template Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <style>
        @import url('http://fonts.cdnfonts.com/css/roboto');
        @import url('http://fonts.cdnfonts.com/css/indira-k');
    </style>

    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/9302266.js"></script>
    <!-- End of HubSpot Embed Code -->

coresight/templates/_jumbo.html
{% load static %}

{% if object_list %}
<div class="jumbotron jumbotron-fluid coresight-bg" style="background-image: linear-gradient(to right, rgba(136, 2, 13, 0.92), rgba(245, 246, 252, 0.73));">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-7 coresight-header">
                <h2 class="title">{{object_list.title}}</h2>
            </div>
            <div>
                <div class="coresight-img-bg" style="background-image: url('{{ object_list.image}}'); background-position: center; background-size: cover">
                </div>
            </div>
       </div>
    </div>
</div>
{% endif %}

coresight/templates/_post_tag.html
{% load static %}
<div class="col-lg-3 col-md-4 col-sm-6 pd-10">
    <div class="card">
        <a href="{% url 'post-detail' slug=post.slug %}">
            {% if post.image %}
            <img src="{{ post.image.url }}" />
            {% else %}
            <img src="{% static 'images/no_image.png' %}" alt="" />
            {% endif %}
        </a>
        <div class="card-body">
        {% comment %} <span class="category thin">{{ post.theme|truncatewords:7 }}</span> {% endcomment %}
        <p class="card-text semi-bold">{{ post.title|truncatechars:40 }}</p>
        {% if post.excerpt %}
        <p class="card-text-small">{{post.excerpt|truncatechars:100}}</p>
        {% else %}
        <p class="card-text-small">{{ post.short_body|default_if_none:""|striptags|safe|truncatechars:100 }}</p>
        {% endif %}
        </div>
        <div class="card-link">
            <a
                class="more"
                href="{% url 'post-detail' slug=post.slug %}"
            >Read More <i class="fa fa-arrow-right"></i></a>
        </div>
    </div>
</div>

coresight/templates/_premium_form.html
{% load static %}

<div class="">
    <div class="form">
        <form action="{% url 'premium_request' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="full_name">Full name</label>
                <input
                    type="text"
                    name="full_name"
                    class="form-control"
                    id="full_name"
                    aria-describedby="firstNameHelp"
                    placeholder="Enter first name"
                >
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input
                    type="email"
                    name="email"
                    class="form-control"
                    id="exampleInputEmail1"
                    aria-describedby="emailHelp"
                    placeholder="Enter email"
                >
            </div>
            <div class="form-group">
                <label for="company">Company</label>
                <input
                    type="text"
                    name="company"
                    class="form-control"
                    id="company"
                    aria-describedby="companyHelp"
                    placeholder="Enter company name"
                >
            </div>
            <div class="form-group">
                <label for="shortMessage">Short Message</label>
                <textarea
                    class="form-control"
                    id="shortMessage"
                    name="short_message"
                    cols="30"
                    rows="5"
                ></textarea>
                <input type="hidden" name="redirected_from" value="{{ request.get_full_path }}">
            </div>
            <button type="submit" class="btn btn-danger btn-block">Submit</button>
        </form>
    </div>
</div>

coresight/templates/_tab_posts.html
<div class="tab-news">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <ul class="nav nav-pills nav-justified">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="pill" href="#featured">Featured News</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#popular">Popular News</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#latest">Latest News</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="featured" class="container tab-pane active">
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-1.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-2.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-3.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                    </div>
                    <div id="popular" class="container tab-pane fade">
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-4.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-5.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-1.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                    </div>
                    <div id="latest" class="container tab-pane fade">
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-2.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-3.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-4.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            
            <div class="col-md-6">
                <ul class="nav nav-pills nav-justified">
                    <li class="nav-item">
                        <a class="nav-link active" data-toggle="pill" href="#m-viewed">Most Viewed</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#m-read">Most Read</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="pill" href="#m-recent">Most Recent</a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div id="m-viewed" class="container tab-pane active">
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-5.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-4.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-3.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                    </div>
                    <div id="m-read" class="container tab-pane fade">
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-2.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-1.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-3.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                    </div>
                    <div id="m-recent" class="container tab-pane fade">
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="{% static 'images/news-350x223-4.jpg' %}" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="img/news-350x223-5.jpg" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                        <div class="tn-news">
                            <div class="tn-img">
                                <img src="img/news-350x223-1.jpg" />
                            </div>
                            <div class="tn-title">
                                <a href="">Lorem ipsum dolor sit amet</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

coresight/templates/_vertical_post_tag.html
{% load static %}
<div class="card pd-10" style="width: 100%;">
    <div class="card-body">
    {% comment %} <span class="category thin">{{ post.theme|truncatewords:7 }}</span> {% endcomment %}
    <h4 class="card-text semi-bold">{{ post.title }}</h4>
    {% if post.summary %}
    <p class="card-text-small">{{post.summary}}</p>
    {% endif %}
    </div>
    <div class="card-link">
        <a
            class="more"
            href="{% url 'databank_detail' post.id %}"
        >Read More <i class="fa fa-arrow-right"></i></a>
    </div>
</div>

coresight/templates/base.html
<!DOCTYPE html>
<html lang="en">

    {% load static %}

    <head>

        {% include '_headers.html' %}

        {% block css %}
        {% endblock css %}
    
    </head>
    
    <body>
        <!-- Top Nav Bar-->
        {% include 'top_navbar.html' %}
        <!-- Top Nav Bar End-->
        <!-- Nav Bar Start -->
        {% include 'nav.html' %}
        <!-- Nav Bar End -->

        <!-- Top News Start-->
        {% block content %}
        {% endblock content %}

        <!-- Footer Start -->
        {% include '_footer.html' %}
        <!-- Footer End -->

        <!-- JavaScript Libraries -->
        {% include '_js.html' %}

        {% block javascript %}
        {% endblock javascript %}
    </body>
</html>

coresight/templates/nav.html
{% load static %}
<div class="bg-red row sticky-top" style="box-shadow: 0px 0px 6px 3px rgba(0,0,0,.1);">
    {% if messages %} 
        {% for message  in messages %}
        <div id="message" class="container">
            <div class="popin alert alert-{{ message.tags }} alert-dimissible text-center mt-2" role="alert">
                <button class="close" data-dismiss="alert"> <span aria-hidden="true">&times;</span></button>
                {{ message }}
            </div>
        </div>
        {% endfor %}
        {% endif %}
    <nav class="navbar container-fluid navbar-expand-lg coresight-nav">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img
                    src="{% static 'images/logo_white.png' %}" alt="CORESIGHT_RESEARCH"
                    width="120"
            >
        </a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
        >
            <i class="fas fa-bars" style="color: #000 !important;"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_researches' %}">All Research</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sector_list' %}">Sectors</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'theme-list' %}">
                        Themes
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'event_list' %}">
                        Events
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'databank_list' %}">
                        Data
                    </a>
                </li>
            </ul>
            <div class="nav-item dropdown search-dropdown">
				<a data-toggle="dropdown" class="nav-item nav-link dropdown-t" href="#"><i class="fa fa-search"></i></a>
				<a data-toggle="dropdown" class="nav-item nav-link dropdown-t d-none" href="#"><i class="fa fa-close"></i></a>
				<div class="dropdown-menu">
					<div>
                        <form method="get" action="{% url 'all_researches' %}">
                            <div class="form-group">
                                <div class="input-group search-box">								
                                    <input type="text" name="q" id="search" class="form-control" placeholder="Search here...">
                                    <div class="input-group-append">
                                        <button type="search" class="btn btn-primary">Search</button>
                                    </div>
                                </div>
                            </div>
                            <div style="margin-bottom: 10px;">
                                <input type="checkbox" name="advanced" id="advancedSearch" disabled>
                                Advanced Search <small style="background-color: #111; color: #fff; padding: 3px; font-size: .2rem !important;">Beta 1.0</small>
                            </div>
                            <div id="advancedSearchForm" class="d-none">
                                <hr>
                                <h5 class="semi-bold">Advanced Search</h5> 
                                <div class="form-group">
                                    <label for="search_type">Alogorithm</label><br>
                                    <small>(Choose how advanced your want you search query to be generated)</small>
                                    <select name="search_type" class="form-control">
                                        <option value="">Select Advanced Search Key</option>
                                        <option value="plain">Plain</option>
                                        <option value="phrase">Phrase</option>
                                        <option value="raw">Raw</option>
                                        <option value="websearch">Web Search</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="rank">Ranking</label>
                                    <div>
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="rank" id="inlineRadio1" value="option1" />
                                            <label class="form-check-label" for="inlineRadio1">Title</label>
                                        </div>
                                        
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="rank" id="inlineRadio2" value="option2" />
                                            <label class="form-check-label" for="inlineRadio2">Body</label>
                                        </div>
                                        
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="rank" id="inlineRadio3" value="option3" />
                                            <label class="form-check-label" for="inlineRadio3">Author</label>
                                        </div>
    
                                        <div class="form-check form-check-inline">
                                            <input class="form-check-input" type="radio" name="rank" id="inlineRadio3" value="option3" />
                                            <label class="form-check-label" for="inlineRadio3">Category</label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>                        
                    </div>
                </div>
            </div>
            {% if not user.is_authenticated %}
                <div class="login">
                    <a type="button" class="nav-link sign-in" data-toggle="modal" data-target="#myModal">
                        Sign In
                    </a>
                    <a href="{% url 'signup' %}">
                        <button
                                class="btn bg-white"
                                type="button"
                        >Register/Subscribe
                        </button>
                    </a>
                </div>
            {% else %}
                <div class="login">
                    {% if user.is_staff %}
                    <a class="nav-link sign-in" href="{% url 'post-list' %}">Production </a>
                    {% endif %}
                    <a class="nav-link" href="{% url 'users:account' %}">
                        <i class="fa fa-user-circle"></i> Dashboard
                    </a>
                    <a href="{% url 'logout' %}?next=/" class="nav-link">
                        <i class="fas fa-sign-out-alt" aria-hidden="true"></i> Logout
                    </a>
                </div>
            {% endif %}
        </div>
    </nav>
</div>

{% include 'login.html' %}

coresight/templates/sitemap.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
        <div class="header p-4">
            <h3> CoreSight Research Sitemap</h3>
            <hr>
        </div>
        <section>
            <h3>Research</h3>
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 pd-10">
                        <a class="text-primary"
                           href="{% url 'all_researches' %}">All Research</a>
                    </div>
                </div>
            </div>
            <hr>
        </section>
        <section>
            <h3>Sectors</h3>
            <div class="container">
                <div class="row">
                {% for sector in sectors %}
                    <div class="col-md-4 col-sm-6 pd-10">
                        <a class="text-primary"
                           href="{% url 'sector_list' %}?sector={{ sector.name }}">{{ sector.name }}</a>
                    </div>
                {% endfor %}
            </div>
            </div>
            <hr>
        </section>
        <section>
            <h3>Themes</h3>
            <div class="container">
                <div class="row">
                {% for theme in themes %}
                    <div class="col-md-4 col-sm-6 pd-10">
                        <a class="text-primary"
                           href="{% url 'theme-list' %}?sector={{ theme.name }}">{{ theme.name }}</a>
                    </div>
                {% endfor %}
            </div>
            </div>
            <hr>
        </section>
        <section>
            <h3>Events</h3>
            <div class="container">
                <div class="row">
                {% for event in events %}
                    <div class="col-md-4 col-sm-6 pd-10">
                        <a class="text-primary" href="{% url 'event_detail' pk=event.id %}">{{ event }}</a>
                    </div>
                {% endfor %}
            </div>
            </div>
            <hr>
        </section>
        <section>
            <h3>Data</h3>
            <div class="container">
                <div class="row">
                {% for databank in databanks %}
                    <div class="col-md-4 col-sm-6 pd-10">
                        <a class="text-primary" href="{% url 'databank_detail' data.id %}">{{ databank }}</a>
                    </div>
                {% endfor %}
            </div>
            </div>
            <hr>
        </section>

    </div>
{% endblock %}